### ISSUE TITLE
How does this work together with composer based magento installations?

### ISSUE THREAD

**Issue by sagikazarmark** [createdbypete/capistrano-magento#5]
Hey there,

First of all: your gem is awesome, I am glad I found it.

I have a question though: recently I found that magento core can be installed using composer as well:

https://github.com/AydinHassan/magento-core-composer-installer

Does this work well together with capistrano based deployment?

**Comment by robinbortlik** [comment]
Hi @sagikazarmark , did you tried it? I'm also curious, what is your experience.

**Comment by sagikazarmark** [comment]
Not yet, will try it in a few days.

**Comment by createdbypete** [comment]
Sorry @sagikazarmark I have not tried it. It could probably be included if you have any luck though so keep me posted/submit a pull request :smile_cat:

**Comment by sagikazarmark** [comment]
Will try.

**Comment by createdbypete** [comment]
You can maybe take a look at using https://github.com/capistrano/composer/  to handle your composer tasks.

**Comment by sagikazarmark** [comment]
That's what I am doing :wink:
